name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - **

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-configuration: [debug, release]

    steps:
      - uses: actions/checkout@v2
      - name: Install .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x
      - name: Execute Unit Tests
        run: dotnet test
      - name: Restore the application
        run: dotnet restore
      - name: Create a package for Windows, Linux, and MacOS
        run: dotnet publish -c ${{ matrix.dotnet-configuration }} -r win-x64,linux-x64,osx-x64
      - name: Remove the pfx
        run: find . -name "*.pfx" -delete
      - name: Upload the Build
        uses: actions/upload-artifact@v2
        with:
          name: build-${{ matrix.dotnet-configuration }}
          path: bin/${{ matrix.dotnet-configuration }}/*
